### ISSUE TITLE
Taxing and paying 

### ISSUE THREAD

**Issue by Neutonic** [seventhroot/elysium#83]
Add a feature that auto taxes and pays players in groups that have been set up.

**Comment by alyphen** [comment]
Delaying this until we have more information. What do we need in terms of:
* Income tax
* Property tax
* Transfer tax
* Wealth tax
* Goods and services tax (VAT)

**Comment by Neutonic** [comment]
Players need the ability to create groups that either take money from players in that group or give them money.Which would have the amount paided or taken over whatever time interval they want. Please do this is hours as players can't understand ticks.. 
Would require a notification every time you've been paid/taxed or if someone refuses to pay (Look below)

For the taxing group you need the other player to accept. /tax accept (nameofgroup) (May need to come up with a better command) But at any point they should also be able to refuse to pay money /tax stop (nameofgroup)
/tax list  - Shows them a list of group they are in/control
/tax modify (time) (money)

**Comment by alyphen** [comment]
From the discussion:

## Database entities

**PaymentGroup**
name: String
owners: List<Character>
players: List<Character>
invites: List<Character>
amount: Int
currency: Currency
interval: Long
balance: Int

**PaymentNotification**
group: PaymentGroup
to: Character
character: Character
date: Long

## Commands

**/payment create [name]** – Creates a tax group with the given name.
**/payment invite [player]** – Invites a player to a tax group.
**/payment join [name]** / **/tax accept [name]** – Joins a tax group. Notify owners.
**/payment leave [name]** – Leaves a tax group. Notify owners.
**/payment withdraw [name]** – Withdraw money into the group.
**/payment deposit [name] [amount]** – Deposit money into the group.

## Other information

Notify all users when payment is taken or given.
Positive amount pays users, negative takes money.
If users are offline, add a notification for when they come back online.
Remove the notification once the player has received it.
